In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [6,7,8]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5)

array([0.26627081, 0.98323177, 0.06795786, 0.71999076, 0.97109979])

In [29]:
np.random.rand(5,5)

array([[0.68946299, 0.90224099, 0.85143784, 0.15670245, 0.50739748],
       [0.35969659, 0.85805319, 0.11195202, 0.49933889, 0.84089073],
       [0.14956309, 0.30984586, 0.59119735, 0.59502727, 0.88212714],
       [0.978598  , 0.00452844, 0.78398939, 0.86413179, 0.70101166],
       [0.72094561, 0.18584928, 0.6061315 , 0.78252798, 0.37051923]])

In [30]:
np.random.randn(2)

array([ 0.16213874, -0.70176666])

In [32]:
np.random.randn(4,4)

array([[-1.71289617,  0.06749105, -0.30550879, -1.54019378],
       [ 2.04233497,  1.76059269,  0.41920419, -2.22375419],
       [ 2.07930624,  0.23154104,  0.62338601, -0.92398049],
       [ 0.85163621,  2.70717067, -0.70648839, -0.56906482]])

In [34]:
np.random.randint(1,199,2)

array([164,   6])

In [35]:
teste = np.arange(0,25)

In [36]:
teste

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
teste.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arrs = teste.reshape(25,1)

In [40]:
arrs

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [41]:
arrs.max()

24

In [42]:
arrs.min()

0

In [43]:
arrs.argmax()

24

In [45]:
arrs.shape

(25, 1)

In [46]:
arrs.dtype

dtype('int32')

In [49]:
from numpy.random import randint

In [50]:
randint(1,120)

56