In [1]:
import numpy as np

In [12]:
arr = np.arange(50).reshape(5,10)

In [13]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
arr2 = np.random.randn(50)

In [19]:
arr2

array([ 0.50812705, -0.59808647,  1.80060503, -0.00779272, -0.2314784 ,
       -0.66838079, -0.32115272,  0.88728006,  0.82380575,  0.4661504 ,
        0.72242405, -0.4948385 , -2.76279554,  0.25843189, -2.37505032,
        0.17670757, -0.46904647,  1.57743303,  0.17106758, -1.24524491,
        2.0836997 ,  2.28413334,  1.25608194, -0.75228957,  1.2265559 ,
       -1.39193663, -1.52410615, -0.13692314,  0.79713486,  0.41585753,
        0.17785623, -0.04999419,  1.54001913, -2.59851781,  0.55133353,
        0.14930776, -0.01920372, -0.32696956,  0.59539097,  1.26020827,
       -0.14015921, -0.422812  , -0.42223608,  0.10698284, -1.16093759,
        0.24150633, -0.3171774 ,  0.05822243, -0.6108305 , -0.50739174])

In [23]:
arr2 = arr2.reshape(10,5)

In [24]:
arr2

array([[ 0.50812705, -0.59808647,  1.80060503, -0.00779272, -0.2314784 ],
       [-0.66838079, -0.32115272,  0.88728006,  0.82380575,  0.4661504 ],
       [ 0.72242405, -0.4948385 , -2.76279554,  0.25843189, -2.37505032],
       [ 0.17670757, -0.46904647,  1.57743303,  0.17106758, -1.24524491],
       [ 2.0836997 ,  2.28413334,  1.25608194, -0.75228957,  1.2265559 ],
       [-1.39193663, -1.52410615, -0.13692314,  0.79713486,  0.41585753],
       [ 0.17785623, -0.04999419,  1.54001913, -2.59851781,  0.55133353],
       [ 0.14930776, -0.01920372, -0.32696956,  0.59539097,  1.26020827],
       [-0.14015921, -0.422812  , -0.42223608,  0.10698284, -1.16093759],
       [ 0.24150633, -0.3171774 ,  0.05822243, -0.6108305 , -0.50739174]])

In [25]:
arr2 = arr2 +arr2

In [26]:
arr2

array([[ 1.01625409, -1.19617293,  3.60121006, -0.01558543, -0.4629568 ],
       [-1.33676159, -0.64230544,  1.77456012,  1.6476115 ,  0.9323008 ],
       [ 1.4448481 , -0.989677  , -5.52559108,  0.51686378, -4.75010063],
       [ 0.35341514, -0.93809294,  3.15486606,  0.34213516, -2.49048982],
       [ 4.1673994 ,  4.56826668,  2.51216388, -1.50457914,  2.45311181],
       [-2.78387326, -3.04821229, -0.27384628,  1.59426971,  0.83171505],
       [ 0.35571245, -0.09998838,  3.08003826, -5.19703561,  1.10266706],
       [ 0.29861553, -0.03840745, -0.65393913,  1.19078195,  2.52041654],
       [-0.28031841, -0.84562399, -0.84447216,  0.21396568, -2.32187518],
       [ 0.48301267, -0.63435479,  0.11644486, -1.22166101, -1.01478349]])

In [27]:
arr2 = arr2 - 10

In [28]:
arr2

array([[ -8.98374591, -11.19617293,  -6.39878994, -10.01558543,
        -10.4629568 ],
       [-11.33676159, -10.64230544,  -8.22543988,  -8.3523885 ,
         -9.0676992 ],
       [ -8.5551519 , -10.989677  , -15.52559108,  -9.48313622,
        -14.75010063],
       [ -9.64658486, -10.93809294,  -6.84513394,  -9.65786484,
        -12.49048982],
       [ -5.8326006 ,  -5.43173332,  -7.48783612, -11.50457914,
         -7.54688819],
       [-12.78387326, -13.04821229, -10.27384628,  -8.40573029,
         -9.16828495],
       [ -9.64428755, -10.09998838,  -6.91996174, -15.19703561,
         -8.89733294],
       [ -9.70138447, -10.03840745, -10.65393913,  -8.80921805,
         -7.47958346],
       [-10.28031841, -10.84562399, -10.84447216,  -9.78603432,
        -12.32187518],
       [ -9.51698733, -10.63435479,  -9.88355514, -11.22166101,
        -11.01478349]])