In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[:3]

array([0, 1, 2])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_arr = arr[:3]

In [19]:
slice_arr

array([0, 1, 2])

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:

slice_arr[:] = 99

In [23]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 99

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [28]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_2d = np.array([[5,10,5],[20,5,4], [8,5,4]])

In [30]:
arr_2d

array([[ 5, 10,  5],
       [20,  5,  4],
       [ 8,  5,  4]])

In [31]:
arr_2d[0,0]

5

In [32]:
arr_2d[0]

array([ 5, 10,  5])

In [33]:
arr_2d[0] = 99

In [34]:
arr_2d

array([[99, 99, 99],
       [20,  5,  4],
       [ 8,  5,  4]])

In [35]:
arr_2d[0,0] = 1000

In [36]:
arr_2d

array([[1000,   99,   99],
       [  20,    5,    4],
       [   8,    5,    4]])

In [37]:
arr_2d[:2]

array([[1000,   99,   99],
       [  20,    5,    4]])

In [38]:
arr_2d[:2,:2]

array([[1000,   99],
       [  20,    5]])

In [39]:
arr_2d[:2,2:]

array([[99],
       [ 4]])

In [40]:
arr2 = np.arange(1,11)

In [41]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 5

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True])

In [44]:
arrb = arr >5

In [45]:
arrb

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True,  True])

In [46]:
arr[arrb]

array([99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr[arr>5]

array([99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr[arr > 11]

array([99, 99, 99])